// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MasterMessage.proto

package org.itstack.demo.iot.gateway.protobuf;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:org.itstack.demo.iot.gateway.protobuf.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string ip = 2;</code>
   */
  java.lang.String getIp();
  /**
   * <code>string ip = 2;</code>
   */
  com.google.protobuf.ByteString
      getIpBytes();

  /**
   * <code>string port = 3;</code>
   */
  java.lang.String getPort();
  /**
   * <code>string port = 3;</code>
   */
  com.google.protobuf.ByteString
      getPortBytes();

  /**
   * <code>string protocolId = 4;</code>
   */
  java.lang.String getProtocolId();
  /**
   * <code>string protocolId = 4;</code>
   */
  com.google.protobuf.ByteString
      getProtocolIdBytes();

  /**
   * <code>string content = 5;</code>
   */
  java.lang.String getContent();
  /**
   * <code>string content = 5;</code>
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string property = 6;</code>
   */
  java.lang.String getProperty();
  /**
   * <code>string property = 6;</code>
   */
  com.google.protobuf.ByteString
      getPropertyBytes();
}
